print('olá, mundo')                                                                                                                    
print('azul')
print('rosa')
print('vermelho')
print('amarelo')
print('branco')
print('preto')
print('dourado')
print('prata')
print('roxo')